import Head from "next/head";
import styles from "/styles/home.module.css";
import Image from "next/image";
import heroLogo from "@/public/assets/hero.png";
import { FaGithub, FaLinkedin } from "react-icons/fa";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image
            src={heroLogo}
            alt="Logo tarefas"
            priority
            className={styles.hero}
          />
        </div>
        <h1 className={styles.title}>
          Sistema feito para você organizar <br /> seus estudos e tarefas
        </h1>

        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+12 posts</span>
          </section>
          <section className={styles.box}>
            <span>+90 comentários</span>
          </section>
        </div>
      </main>
      <footer
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          marginTop: "2rem",
        }}
      >
        <p style={{ color: "#fff", fontSize: "1.5rem" }}>
          Feito por Dudu Oliveira | 2024
        </p>
        <ul
          style={{
            display: "flex",
            alignItems: "center",
            gap: "15px",
            marginTop: "1rem",
          }}
        >
          <li>
            <a href="https://github.com/Eduardo-DevJs" target="_blank">
              <FaGithub size={40} color="#fff" />
            </a>
          </li>
          <li>
            <a
              href="https://www.linkedin.com/in/eduardo-oliveira-liria-849467246/"
              target="_blank"
            >
              <FaLinkedin size={40} color="#fff" />
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
}
